# https://www.netlify.com/docs/netlify-toml-reference/
[dev]
  base = "./"
  publish = "./_site/"
  command = "npx @11ty/eleventy --serve"
  functions = "api"
[build]
  base = "./"
  publish = "./_site/"
  command = "npm run build && eleventy"
  functions = "api"
